###
GET {{baseUrl}}/businesses
###
POST {{baseUrl}}/businesses
Content-Type: application/json

{
  "business_legal_name": "4th Test Corp",
  "ein": "456895623",
  "industry_id": 1,
  "city": "Dallas",
  "state": "TX"
}
###
GET {{baseUrl}}/businesses/4
###
GET {{baseUrl}}/businesses?state=NY
###
GET {{baseUrl}}/businesses?industry_id=1
###
GET {{baseUrl}}/businesses?city=New York
###
Get {{baseUrl}}/health
###
Get {{baseUrl}}/debug/ping
###
Get {{baseUrl}}/debug/bindings
###
Get {{baseUrl}}/debug/where
###
PATCH {{baseUrl}}/businesses/4
Content-Type: application/json

{
  "city": "Pheonix",
  "state": "AZ"
}
###
DELETE {{baseUrl}}/businesses/6