POST {{baseUrl}}/assignments
Content-Type: application/json
api-key: {{apiKey}}

{
    "deal_role": "Opener",
    "deal_id": 2
}
###
GET {{baseUrl}}/assignments/6
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/assignments/6
Content-Type: application/json
api-key: {{apiKey}}

{
    "employee_id": 2 
}
###
GET {{baseUrl}}/assignments
api-key: {{apiKey}}
###
DELETE {{baseUrl}}/assignments/7
api-key: {{apiKey}}