###
GET {{baseUrl}}/businesses
###
POST {{baseUrl}}/businesses
Content-Type: application/json

{
  "business_legal_name": "4th Test Corp",
  "ein": "456895623",
  "industry_id": 1,
  "city": "Dallas",
  "state": "TX"
}
###
GET {{baseUrl}}/businesses/4
###
GET {{baseUrl}}/businesses?state=NY
###
GET {{baseUrl}}/businesses?industry_id=1
###
GET {{baseUrl}}/businesses?city=New York
###
PATCH {{baseUrl}}/businesses/4
Content-Type: application/json

{
  "city": "Pheonix",
  "state": "AZ",
  "start_date": "2001-12-31"
}
###
DELETE {{baseUrl}}/businesses/4