POST {{baseUrl}}/deals
Content-Type: application/json
api-key: {{apiKey}}

{
    "date_processed": "04/29/2025",
    "package_id": 3
}
###
GET {{baseUrl}}/deals/1
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/deals/1
Content-Type: application/json
api-key: {{apiKey}}

{
    "stage": "Offers"
}
###
GET {{baseUrl}}/deals
api-key: {{apiKey}}
###
DELETE {{baseUrl}}/deals/1 HTTP/1.1
api-key: {{apiKey}}