POST {{baseUrl}}/fundings
Content-Type: application/json
api-key: {{apiKey}}

{
    "date_funded": "5/4/2026",
    "offer_id": 3
}
###
GET {{baseUrl}}/fundings/1
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/fundings/1
Content-Type: application/json
api-key: {{apiKey}}

{
    "points": 12
}
###
GET {{baseUrl}}/fundings
api-key: {{apiKey}}
###
DELETE {{baseUrl}}/fundings/1
api-key: {{apiKey}}