GET {{baseUrl}}/industries
api-key: {{apiKey}}
###
GET {{baseUrl}}/industries/1 HTTP/1.1
api-key: {{apiKey}}
###
GET {{baseUrl}}/industries/2
api-key: {{apiKey}}
###
POST {{baseUrl}}/industries HTTP/1.1
Content-Type: application/json
api-key: {{apiKey}}

{
    "industry": "Submissions" 
}
###
PATCH {{baseUrl}}/industries/2
Content-Type: application/json
api-key: {{apiKey}}

{
    "airtable_id": null
}
###
DELETE {{baseUrl}}/industries/5 HTTP/1.1
api-key: {{apiKey}}