POST {{baseUrl}}/lenders
Content-Type: application/json
api-key: {{apiKey}}

{
    "lender": "Everest",
    "product": "MCA"
}
###
GET {{baseUrl}}/lenders/1
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/lenders/1
Content-Type: application/json
api-key: {{apiKey}}

{
    "min_revenue": 3000
}
###
GET {{baseUrl}}/lenders
api-key: {{apiKey}}
###
DELETE {{baseUrl}}/lenders/1
api-key: {{apiKey}}

