GET {{baseUrl}}/merchants HTTP/1.1
api-key: {{apiKey}}
###
POST {{baseUrl}}/merchants HTTP/1.1
Content-Type: application/json
api-key: {{apiKey}}

{
    "name": "John Saitram",
    "ssn": "123456789",
    "date_of_birth": "2003-12-13"
}
###
POST {{baseUrl}}/merchants HTTP/1.1
Content-Type: application/json
api-key: {{apiKey}}

{
    "name": "Imani Stewart",
    "ssn": "456789123",
    "date_of_birth": "2002-10-30"
}
###
GET {{baseUrl}}/merchants/1 HTTP/1.1
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/merchants/5
Content-Type: application/json
api-key: {{apiKey}}

{
    "address": "123 main st"
}
###
DELETE {{baseUrl}}/merchants/6 HTTP/1.1
api-key: {{apiKey}}