POST {{baseUrl}}/offers
Content-Type: application/json
api-key: {{apiKey}}

{
    "amount": 80000,
    "submission_id": 2
}
###
GET {{baseUrl}}/offers/2
api-key: {{apiKey}}
###
PATCH {{baseUrl}}/offers/2
Content-Type: application/json
api-key: {{apiKey}}

{
    "payment_cycles": 32,
    "payment_frequency": "Weekly"
}
###
GET {{baseUrl}}/offers
api-key: {{apiKey}}
###
DELETE {{baseUrl}}/offers/2
api-key: {{apiKey}}